In [1]:
#importing the dataset
import pandas as pd

import numpy as np


dataset = pd.read_csv("heart.csv")

In [2]:
dataset.head(10)

dataset.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [3]:
del dataset["Sex"]

x = dataset.iloc[:,0:-1].values

y = dataset.iloc[:,-1]

print(x[:6])
print(y[:5])

[[40 'ATA' 140 289 0 'Normal' 172 'N' 0.0 'Up']
 [49 'NAP' 160 180 0 'Normal' 156 'N' 1.0 'Flat']
 [37 'ATA' 130 283 0 'ST' 98 'N' 0.0 'Up']
 [48 'ASY' 138 214 0 'Normal' 108 'Y' 1.5 'Flat']
 [54 'NAP' 150 195 0 'Normal' 122 'N' 0.0 'Up']
 [39 'NAP' 120 339 0 'Normal' 170 'N' 0.0 'Up']]
0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [4]:
#Encoding categorical data
# pd.set_option("display.max_rows",15)
# print(dataset.iloc[:,6])

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# dataset.iloc[:,1] =label_encoder.fit_transform(dataset.iloc[:,1])
x[:,7] = label_encoder.fit_transform(x[:,7])
print(x[:6])
print(y[:5])
# x[5]

[[40 'ATA' 140 289 0 'Normal' 172 0 0.0 'Up']
 [49 'NAP' 160 180 0 'Normal' 156 0 1.0 'Flat']
 [37 'ATA' 130 283 0 'ST' 98 0 0.0 'Up']
 [48 'ASY' 138 214 0 'Normal' 108 1 1.5 'Flat']
 [54 'NAP' 150 195 0 'Normal' 122 0 0.0 'Up']
 [39 'NAP' 120 339 0 'Normal' 170 0 0.0 'Up']]
0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [5]:
# dataset["ExerciseAngina"]=label_encoder.fit_transform(dataset["ExerciseAngina"])
# dataset

In [6]:
#OneHotEncodeing Encoding
#pd.set_option("display.max_rows",None)
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct  =  ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [1])],remainder = "passthrough" )
# ct1 = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [9])],remainder = "passthrough" )
# ct2 = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [11])],remainder = "passthrough" )
# ct3 = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [16])],remainder = "passthrough" )
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x =ct.fit_transform(x)
# dataset = ct1.fit_transform(dataset)
# dataset = ct2.fit_transform(dataset)
# dataset = ct3.fit_transform(dataset)

print(x[:6])
print(y[:5])
# x = np.array(x)

[[0.0 1.0 0.0 0.0 40 140 289 0 'Normal' 172 0 0.0 'Up']
 [0.0 0.0 1.0 0.0 49 160 180 0 'Normal' 156 0 1.0 'Flat']
 [0.0 1.0 0.0 0.0 37 130 283 0 'ST' 98 0 0.0 'Up']
 [1.0 0.0 0.0 0.0 48 138 214 0 'Normal' 108 1 1.5 'Flat']
 [0.0 0.0 1.0 0.0 54 150 195 0 'Normal' 122 0 0.0 'Up']
 [0.0 0.0 1.0 0.0 39 120 339 0 'Normal' 170 0 0.0 'Up']]
0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [7]:

ct1 = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [12])],remainder = "passthrough" )
x = ct1.fit_transform(x)
print(x[:6])
print(y[:5])

[[0.0 0.0 1.0 0.0 1.0 0.0 0.0 40 140 289 0 'Normal' 172 0 0.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 49 160 180 0 'Normal' 156 0 1.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 37 130 283 0 'ST' 98 0 0.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 48 138 214 0 'Normal' 108 1 1.5]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 54 150 195 0 'Normal' 122 0 0.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 39 120 339 0 'Normal' 170 0 0.0]]
0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [8]:
x = np.array(x)
x[:5]

array([[0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40, 140, 289, 0, 'Normal',
        172, 0, 0.0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 49, 160, 180, 0, 'Normal',
        156, 0, 1.0],
       [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 37, 130, 283, 0, 'ST', 98, 0,
        0.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 48, 138, 214, 0, 'Normal',
        108, 1, 1.5],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 54, 150, 195, 0, 'Normal',
        122, 0, 0.0]], dtype=object)

In [9]:
# #Declare independent and dependent variable
# pd.set_option("display.max_rows",None)
# pd.set_option("display.max_columns",None)
# dataset = pd.DataFrame(dataset)
ct2 = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [11])],remainder = "passthrough" )
x = ct2.fit_transform(x)
# x = np.array(x)
# x[:5]
print(x[:6])
print(y[:5])

[[0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 40 140 289 0 172 0 0.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 49 160 180 0 156 0 1.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 37 130 283 0 98 0 0.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 48 138 214 0 108 1 1.5]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 54 150 195 0 122 0 0.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 39 120 339 0 170 0 0.0]]
0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [10]:
#Splitting Data Set
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30, random_state = 570)





print(x_train[:6])
print(y_train[:5])

[[0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 48 120 260 0 115 0 2.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 72 160 0 0 114 0 1.6]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 54 150 195 0 122 0 0.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 39 110 280 0 150 0 0.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 41 110 250 0 142 0 0.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 70 140 0 1 157 1 2.0]]
251    1
336    0
4      0
216    1
37     0
Name: HeartDisease, dtype: int64

In [11]:
#Standard SCaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train =sc.fit_transform(x_train)
x_train = np.array(x_train)
x_test =sc.fit_transform(x_test)
x_test = np.array(x_test)
print(x_train[:6])
print(y_train[:5])

[[-0.50632013  0.81437856 -0.49171079 -0.25431598  0.99688957 -0.88226603
   0.94246236 -0.50145986 -0.53050648 -0.22903933 -0.56862387 -0.68250761
   0.5581186  -0.53532527 -0.84667599 -0.80646488  1.07399562]
 [ 1.97503503 -1.22793017 -0.49171079 -0.25431598  0.99688957 -0.88226603
  -1.06105034 -0.50145986  1.88499111 -0.22903933  2.00748802  1.55590815
  -1.79318896 -0.53532527 -0.88584063 -0.80646488  0.69519865]
 [-0.50632013  0.81437856 -0.49171079 -0.25431598 -1.00312013  1.13344497
  -1.06105034 -0.50145986  1.88499111 -0.22903933  0.07540411  0.99630421
  -0.02970829 -0.53532527 -0.57252354 -0.80646488 -0.81998924]
 [-0.50632013  0.81437856 -0.49171079 -0.25431598  0.99688957 -0.88226603
   0.94246236 -0.50145986 -0.53050648 -0.22903933 -1.53466582 -1.24211155
   0.73898841 -0.53532527  0.52408628 -0.80646488 -0.81998924]
 [-0.50632013 -1.22793017  2.03371581 -0.25431598 -1.00312013  1.13344497
  -1.06105034  1.99417757 -0.53050648 -0.22903933 -1.31998983 -1.24211155
   0.4676837  -0.53532527  0.21076919 -0.80646488 -0.81998924]
 [-0.50632013  0.81437856 -0.49171079 -0.25431598  0.99688957 -0.88226603
   0.94246236 -0.50145986 -0.53050648 -0.22903933  1.79281203  0.43670027
  -1.79318896  1.86802315  0.79823873  1.2399796   1.07399562]]
251    1
336    0
4      0
216    1
37     0
Name: HeartDisease, dtype: int64

In [12]:
#create Model


from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

for i in range(100):
    classifier = LogisticRegression(random_state = i)
    classifier.fit(x_train, y_train)
    y_pred  = classifier.predict(x_test)
#     cm = confusion_matrix(y_test, y_pred)
    print(accuracy_score(y_test,y_pred)+i)

0.855072463768116
1.855072463768116
2.855072463768116
3.855072463768116
4.855072463768116
5.855072463768116
6.855072463768116
7.855072463768116
8.855072463768115
9.855072463768115
10.855072463768115
11.855072463768115
12.855072463768115
13.855072463768115
14.855072463768115
15.855072463768115
16.855072463768117
17.855072463768117
18.855072463768117
19.855072463768117
20.855072463768117
21.855072463768117
22.855072463768117
23.855072463768117
24.855072463768117
25.855072463768117
26.855072463768117
27.855072463768117
28.855072463768117
29.855072463768117
30.855072463768117
31.855072463768117
32.85507246376812
33.85507246376812
34.85507246376812
35.85507246376812
36.85507246376812
37.85507246376812
38.85507246376812
39.85507246376812
40.85507246376812
41.85507246376812
42.85507246376812
43.85507246376812
44.85507246376812
45.85507246376812
46.85507246376812
47.85507246376812
48.85507246376812
49.85507246376812
50.85507246376812
51.85507246376812
52.85507246376812
53.85507246376812
54.85507246376812
55.85507246376812
56.85507246376812
57.85507246376812
58.85507246376812
59.85507246376812
60.85507246376812
61.85507246376812
62.85507246376812
63.85507246376812
64.85507246376811
65.85507246376811
66.85507246376811
67.85507246376811
68.85507246376811
69.85507246376811
70.85507246376811
71.85507246376811
72.85507246376811
73.85507246376811
74.85507246376811
75.85507246376811
76.85507246376811
77.85507246376811
78.85507246376811
79.85507246376811
80.85507246376811
81.85507246376811
82.85507246376811
83.85507246376811
84.85507246376811
85.85507246376811
86.85507246376811
87.85507246376811
88.85507246376811
89.85507246376811
90.85507246376811
91.85507246376811
92.85507246376811
93.85507246376811
94.85507246376811
95.85507246376811
96.85507246376811
97.85507246376811
98.85507246376811
99.85507246376811

In [13]:
y_pred  = classifier.predict(x_test)
y_pred

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[ 98  20]
 [ 20 138]]
0.855072463768116